#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username: postgres
#spring.datasource.password: postgres
#spring.jpa.hibernate.ddl-auto: create


spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 20MB
      max-request-size: 20MB


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: false
    change-log: "classpath:db/db.changelog-master.xml"

logging:
  level:
    org.hibernate.type: TRACE




