TRUNCATE TABLE users  CASCADE;
TRUNCATE TABLE posts  CASCADE;
TRUNCATE TABLE post_comments  CASCADE;
TRUNCATE TABLE post_votes  CASCADE;
TRUNCATE TABLE tags  CASCADE;
TRUNCATE TABLE tag_to_post  CASCADE;
TRUNCATE TABLE captcha_codes  CASCADE;
TRUNCATE TABLE global_settings  CASCADE;